name: Test
on: [push]
jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
        - bench
        - bench_deploy
        - benchmarker-only
        - dev
        - standalone
        - webapp
        include:
        - target: bench
          host: bench
        - target: bench_deploy
          host: bench
        - target: benchmarker-only
          host: bench
        - target: dev
          host: dev
        - target: standalone
          host: webapp
        - target: webapp
          host: webapp

    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Check syntax
      run: |
        ansible-playbook --syntax-check ${{ matrix.target }}.yml

    - name: Run ansible-playbook
      run: |
        ansible-playbook --verbose --inventory=${{ matrix.host }}, --connection=local ${{ matrix.target }}.yml
